#!/usr/bin/env sh
LUADIR="$(brew --prefix luajit)"
# Make LuaRocks (5.1 tree) visible to the Neovim process
eval "$(luarocks --lua-dir="$LUADIR" --lua-version=5.1 --tree="$(pwd)/.rocks" path --bin)"

exec nvim --headless -u tests/minimal_init.lua \
  --cmd 'set loadplugins' \
  -l "$@"
